[package]
name = "falling-rust"
version = "0.2.0"
authors = ["osuology www.osuology.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
rand = "0.7.0"